sudo: false
language: java
before_install:
  - jdk_switcher use openjdk6
  - sed -i "s|\[JDK6\]|$JAVA_HOME|g" etc/toolchains.xml
  - jdk_switcher use oraclejdk8
branches:
  except:
    - /.*wip.*/i
install:
  - mvn install -DskipTests=true -B -V -t etc/toolchains.xml
script: "mvn verify -t etc/toolchains.xml"
after_success:
- mvn test jacoco:report coveralls:report -t etc/toolchains.xml
- "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && [ ${TRAVIS_BRANCH} = 'java6-compliant' ] && mvn clean deploy -DskipTests --settings ./etc/deploy-settings.xml -t etc/toolchains.xml"
