name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      - name: Prepare
        run: ./mvnw --version
      - name: Build and test
        run: ./mvnw --threads 1C verify
      - name: Report code coverage
        if: ${{ github.ref == 'refs/heads/master' && success() }}
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: ./mvnw test jacoco:report coveralls:report -DrepoToken=$COVERALLS_TOKEN
      - name: Publish
        if: ${{ github.ref == 'refs/heads/master' && success() }}
        run: ./mvnw clean deploy -DskipTests --settings ./deploy-settings.xml

